logging.level: debug
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0600

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false


# filebeat.autodiscover:
#   providers:
#     - type: docker
#       templates:
#         - config:
#             - type: container
#               paths:
#                 - /var/lib/docker/containers/${data.docker.container.id}/*.log

filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: simple-php-website-php-apache-environment:latest
          config:
            - type: container
              multiline.type: pattern
              multiline.pattern: '^[0-9]{1,2}-[0-9]{1,2}-[0-9]{4}'
              multiline.negate: false
              multiline.match: after
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log

logging:
  driver: "json-file"
  options:
    max-size: 10m
    max-file: "3"
    labels: "production_status"
    env: "os"

processors:
  # The following example enriches each event with the machine's local time zone
  # offset from UTC.
  #
  - add_locale:
      format: abbreviation
  #
  # The following example enriches each event with host metadata.
  #
  - add_host_metadata: ~

#setup.kibana:
#   host: "kibana-01:5601"
#output.elasticsearch:
#  hosts: '${ELASTICSEARCH_HOSTS:es-node-01:9200}'
output.logstash:
  hosts: ["logstash-01:5400"]
